# Generated by Django 6.0.1 on 2026-01-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuration'},
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CUSTOM', '--- Manuale ---'), ('HTTP', 'Web Server (HTTP - 80)'), ('HTTPS', 'Web Sicuro (HTTPS - 443)'), ('FTP', 'File Transfer (FTP - 21)'), ('DNS', 'Nomi Dominio (DNS - 53)'), ('SSH', 'Secure Shell (SSH - 22)')], default='CUSTOM', max_length=10, verbose_name='Tipo Servizio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome Servizio'),
        ),
    ]
