# Generated by Django 6.0.1 on 2026-01-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_config_options_service_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nome Servizio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('CUSTOM', '--- Manuale ---'), ('HTTP', 'HTTP - 80'), ('HTTPS', 'HTTPS - 443'), ('FTP', 'FTP - 21'), ('DNS', 'DNS - 53'), ('SSH', 'SSH - 22')], default='CUSTOM', max_length=10, verbose_name='Tipo Servizio'),
        ),
    ]
